version: '3.7'

services:
  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - .env-prod
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
    env_file:
      - .env-prod
    container_name: app
    command: [ "scripts/run.sh" ]
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  database:
